
package cn.ruanwenjun.crm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import cn.ruanwenjun.domain.Noticebill;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.ruanwenjun.cn/")
@XmlSeeAlso({
})
public interface ICustomerService {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.ruanwenjun.crm.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.ruanwenjun.crm.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerNotAssociat", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindCustomerNotAssociat")
    @ResponseWrapper(localName = "findCustomerNotAssociatResponse", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindCustomerNotAssociatResponse")
    public List<Customer> findCustomerNotAssociat();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.ruanwenjun.crm.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerHasAssociat", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindCustomerHasAssociat")
    @ResponseWrapper(localName = "findCustomerHasAssociatResponse", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindCustomerHasAssociatResponse")
    public List<Customer> findCustomerHasAssociat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "editCustomerAssociat", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.EditCustomerAssociat")
    @ResponseWrapper(localName = "editCustomerAssociatResponse", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.EditCustomerAssociatResponse")
    public void editCustomerAssociat(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeCustomerAssociat", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.RemoveCustomerAssociat")
    @ResponseWrapper(localName = "removeCustomerAssociatResponse", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.RemoveCustomerAssociatResponse")
    public void removeCustomerAssociat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdByAddress", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByAddressResponse", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindDecidedzoneIdByAddressResponse")
    public String findDecidedzoneIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.ruanwenjun.crm.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.ruanwenjun.cn/", className = "cn.ruanwenjun.crm.FindAllResponse")
    public List<Customer> findAll();

	
}
